//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.30 at 12:04:37 AM ALMT 
//

package kz.gov.example.esutd.soap.model;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import lombok.Data;

/**
 * <p>Java class for ContractDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContractDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Operation" type="{http://10.61.40.133/shep/bip-sync-wss-gost/}OperationType"/&gt;
 *         &lt;element name="Contract" type="{http://10.61.40.133/shep/bip-sync-wss-gost/}ContractType" minOccurs="0"/&gt;
 *         &lt;element name="Employee" type="{http://10.61.40.133/shep/bip-sync-wss-gost/}EmployeeType" minOccurs="0"/&gt;
 *         &lt;element name="Employer" type="{http://10.61.40.133/shep/bip-sync-wss-gost/}EmployerType" minOccurs="0"/&gt;
 *         &lt;element name="TerminationInfo" type="{http://10.61.40.133/shep/bip-sync-wss-gost/}TerminationInfoType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@Data
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContractDataType", propOrder = {
    "operation",
    "contract",
    "employee",
    "employer",
    "terminationInfo"
})
public class ContractDataType {

    @XmlElement(name = "Operation", required = true)
    @XmlSchemaType(name = "string")
    protected OperationType operation;
    
    @XmlElement(name = "Contract")
    protected ContractType contract;
    
    @XmlElement(name = "Employee")
    protected EmployeeType employee;
    
    @XmlElement(name = "Employer")
    protected EmployerType employer;
    
    @XmlElement(name = "TerminationInfo")
    protected TerminationInfoType terminationInfo;
}
