//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.30 at 12:04:37 AM ALMT 
//


package kz.gov.example.esutd.soap.model;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import lombok.Data;

/**
 * <p>Java class for EmployerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmployerType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EmployerId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BIN" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="KatoCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EmployerType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LegalAddress" type="{http://10.61.40.133/shep/bip-sync-wss-gost/}AddressType"/&gt;
 *         &lt;element name="Contacts" type="{http://10.61.40.133/shep/bip-sync-wss-gost/}ContactsType" minOccurs="0"/&gt;
 *         &lt;element name="BankName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BIK" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AccountNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@Data
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmployerType", propOrder = {
    "employerId",
    "bin",
    "name",
    "katoCode",
    "employerType",
    "legalAddress",
    "contacts",
    "bankName",
    "bik",
    "accountNumber"
})
public class EmployerType {

    @XmlElement(name = "EmployerId", required = true)
    protected String employerId;
    @XmlElement(name = "BIN", required = true)
    protected String bin;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "KatoCode")
    protected String katoCode;
    @XmlElement(name = "EmployerType")
    protected String employerType;
    @XmlElement(name = "LegalAddress", required = true)
    protected AddressType legalAddress;
    @XmlElement(name = "Contacts")
    protected ContactsType contacts;
    @XmlElement(name = "BankName")
    protected String bankName;
    @XmlElement(name = "BIK")
    protected String bik;
    @XmlElement(name = "AccountNumber")
    protected String accountNumber;

}
